apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: bWluaWF1dGhrZXlram56ZGZ2aGprdWxzZXJ1OG9zZGdyZmhuajM0dGVxODA5cXUyMzgyaGFzZmdkcm95aDhxM3Q0ODl5cTN0NGhhZWdmcnMy
---
apiVersion: v1
kind: Secret
metadata:
  name: notif-db-secret
type: Opaque
data:
  password: eW91cl9zZWN1cmVfcGFzc3dvcmRfaGVyZTI=